name: CI
on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

env:
  DISPLAY: ':99'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Xvfb - install and run
        run: |
          sudo apt-get install -y xvfb
          Xvfb -ac ${{ env.DISPLAY }} -screen 0 1280x780x24 &
      - uses: julia-actions/setup-julia@v1
        with:
          # Warning: It is strongly recommended to wrap this value in quotes.
          #          Otherwise, the YAML parser used by GitHub Actions parses certain
          #          versions as numbers which causes the wrong version to be selected.
          #          For example, `1.10` may be parsed as `1.1`.
          version: '1.10'
      - uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
